name = "virallink2"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "view-counter-db"
database_id = "8d583c88-0aeb-495f-b289-c22ba88d4950"
